#!/bin/bash

#command to check and see if sounds are enabled
#xfconf-query -c xsettings -p /Net/EnableEventSounds 
#command to check sound theme name
#xfconf-query -c xsettings -p /Net/SoundThemeName
#command to find desktop-login sound for a given theme
#find  /usr/share/sounds/theme-name/ |grep desktop-login

customsound=$(cat ~/.config/startupsound.conf)
echo custom sound is $customsound

soundstatus=$(xfconf-query -c xsettings -p /Net/EnableEventSounds)
echo sound status is $soundstatus

soundthemename=$(xfconf-query -c xsettings -p /Net/SoundThemeName)
echo sound theme is $soundthemename

defaultsound=$(find  /usr/share/sounds/$soundthemename/ |grep desktop-login)
echo default sound is $defaultsound

vboxtest=$(cat /proc/modules |grep vboxguest)
echo vboxtest is $vboxtest

#set Master Surround Channel volume to 70% only in VirtualBox

#for VirtualBox VMs that use Master Surround
if [ "$vboxtest" != "" ]; then
	amixer -c 0 sset "Master Surround" 21
fi

if [ "$customsound" = "" ]; then
	if [ "$soundstatus" = "true" ]; then
		cvlc --play-and-exit file://$defaultsound 
		exit 0
	else
		exit 0
	fi
else
	if [ "$soundstatus" = "true" ]; then
		cvlc --play-and-exit file://$customsound 
		exit 0
	else
		exit 0
	fi
fi

exit 0